using TransitNovaUI.BusinessLayer.ApiInterfaceServices.Shared.Notifications.Commands;

namespace TransitNovaUI.BusinessLayer.ApiInterfaceServices.Shared.Notifications.Segregation;

public interface ISharedNotificationsCommand : IMarkAllNotificationsReadCommandService
{
}