services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: transitnova-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\" || /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - transitnova





  transitnova_api:
    build:
      context: .
      dockerfile: Src/Dockerfile
    container_name: transitnova-api
    ports:
      - "5200:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      MVC__Host: http://transitnova-ui:80
      PaymentSettings__BaseUrl: http://transitnova-payment:80 
      JWT__Key: "${JWT_KEY}"
      PaymentSettings__PublicKey: "${PaymentSettings__PublicKey}"
      ConnectionStrings__DefaultConnection: "${ConnectionStrings__ApiDefaultConnection}"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://transitnova-seq:5341/ingest/otlp/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    depends_on:
      sqlserver:
        condition: service_healthy
      transitnova-payment:
        condition: service_started
    networks:
      - transitnova





  transitnova-payment:
    build:
      context: .
      dockerfile: TransitNovaPayment/Dockerfile
    container_name: transitnova-payment
    ports:
      - "5300:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      PaymentSettings__PrivateKey: "${PaymentSettings__PrivateKey}"
      ConnectionStrings__DefaultConnection: "${ConnectionStrings__PaymentDefaultConnection}"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://transitnova-seq:5341/ingest/otlp/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - transitnova





  transitnova-ui:
    build:
      context: .
      dockerfile: Ui/Dockerfile
    container_name: transitnova-ui
    ports:
      - "5169:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    depends_on:
      - transitnova_api
    networks:
      - transitnova

  transitnova-seq:
    image: datalust/seq:latest
    container_name: transitnova-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True
    volumes:
      - seq-data:/data
    networks:
      - transitnova
    ports:
      - "5341:5341"
      - "8081:80"

networks:
  transitnova:
    driver: bridge

volumes:
  sqlserver-data:
  seq-data:
