using Microsoft.Extensions.DependencyInjection.Extensions;
using TransitNovaUI.BusinessLayer.Common.APIHelper.Http;

namespace TransitNova.UI;

public static class BackendApiServiceCollectionExtensions
{
    public static IServiceCollection AddTransitNovaApiClients(this IServiceCollection services)
    {
        services.AddHttpClient();
        services.TryAddScoped<IHttpHandler, HttpHandler>();

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Command.AdminBundlesCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Command.AdminBundlesCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Bundles.Commands.ICreateBundleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Command.AdminBundlesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Bundles.Commands.IDeleteBundleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Command.AdminBundlesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Bundles.Commands.IUpdateBundleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Command.AdminBundlesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Bundles.Segregations.Commands.IAdminBundlesCommand>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Command.AdminBundlesCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Query.AdminBundlesQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Query.AdminBundlesQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Bundles.Queries.IGetBundleByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Query.AdminBundlesQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Bundles.Queries.IGetBundlesQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Bundles.Query.AdminBundlesQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Carriers.Command.AdminCarriersCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Carriers.Command.AdminCarriersCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Carriers.Commands.IDeleteCarrierCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Carriers.Command.AdminCarriersCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Cities.Command.AdminCitiesCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Cities.Command.AdminCitiesCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Cities.Commands.ICreateCityCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Cities.Command.AdminCitiesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Cities.Commands.IDeleteCityCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Cities.Command.AdminCitiesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Cities.Commands.IUpdateCityCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Cities.Command.AdminCitiesCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Cities.Query.AdminCitiesQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Cities.Query.AdminCitiesQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Cities.Queries.IFilterCitiesQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Cities.Query.AdminCitiesQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Cities.Queries.IGetCityByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Cities.Query.AdminCitiesQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Dashboard.Query.AdminDashboardQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Dashboard.Query.AdminDashboardQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Dashboard.Queries.IGetAdminDashboardQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Dashboard.Query.AdminDashboardQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Governments.Command.AdminGovernmentsCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Governments.Command.AdminGovernmentsCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Governments.Commands.ICreateGovernmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Governments.Command.AdminGovernmentsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Governments.Commands.IDeleteGovernmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Governments.Command.AdminGovernmentsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Governments.Commands.IUpdateGovernmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Governments.Command.AdminGovernmentsCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Governments.Query.AdminGovernmentsQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Governments.Query.AdminGovernmentsQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Governments.Queries.IGetGovernmentByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Governments.Query.AdminGovernmentsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Governments.Queries.IGetGovernmentsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Governments.Query.AdminGovernmentsQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.OperationManagers.Query.AdminOperationManagersQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.OperationManagers.Query.AdminOperationManagersQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.OperationManagers.Queries.IGetActiveOperationManagersQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.OperationManagers.Query.AdminOperationManagersQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.OperationManagers.Queries.IGetOperationManagerByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.OperationManagers.Query.AdminOperationManagersQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.OperationManagers.Queries.IGetOperationManagerHandledCarriersQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.OperationManagers.Query.AdminOperationManagersQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.OperationManagers.Queries.IGetOperationManagerHandledShipmentsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.OperationManagers.Query.AdminOperationManagersQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.OperationManagers.Queries.IGetOperationManagersQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.OperationManagers.Query.AdminOperationManagersQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Command.AdminRolesCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Command.AdminRolesCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Roles.Commands.ICreateRoleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Command.AdminRolesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Roles.Commands.IDeleteRoleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Command.AdminRolesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Roles.Commands.IUpdateRoleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Command.AdminRolesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Roles.Commands.IUpdateRoleMembersCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Command.AdminRolesCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Query.AdminRolesQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Query.AdminRolesQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Roles.Queries.IGetRoleByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Query.AdminRolesQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Roles.Queries.IGetRoleMembersQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Query.AdminRolesQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Roles.Queries.IGetRolesQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Roles.Query.AdminRolesQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Subscriptions.Query.AdminSubscriptionsQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Subscriptions.Query.AdminSubscriptionsQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Subscriptions.Queries.IGetBundleSubscribersQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Subscriptions.Query.AdminSubscriptionsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Subscriptions.Queries.IGetSubscriptionByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Subscriptions.Query.AdminSubscriptionsQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Users.Query.AdminUsersQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Users.Query.AdminUsersQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Users.Queries.IFilterUsersQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Users.Query.AdminUsersQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Users.Queries.IGetUserDetailsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Users.Query.AdminUsersQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Command.AdminVehiclesCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Command.AdminVehiclesCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Vehicles.Commands.ICreateVehicleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Command.AdminVehiclesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Vehicles.Commands.IDeleteVehicleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Command.AdminVehiclesCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Query.AdminVehiclesQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Query.AdminVehiclesQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Vehicles.Queries.IGetActiveVehiclesQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Query.AdminVehiclesQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Vehicles.Queries.IGetVehicleByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Query.AdminVehiclesQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Vehicles.Queries.IGetVehicleByPlateNumberQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Query.AdminVehiclesQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Vehicles.Queries.IGetVehiclesQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Vehicles.Query.AdminVehiclesQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Warehouses.Command.AdminWarehousesCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Warehouses.Command.AdminWarehousesCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Warehouses.Commands.ICreateWarehouseCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Warehouses.Command.AdminWarehousesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Warehouses.Commands.IDeleteWarehouseCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Warehouses.Command.AdminWarehousesCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Warehouses.Commands.IUpdateWarehouseCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Warehouses.Command.AdminWarehousesCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Warehouses.Query.AdminWarehousesQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Warehouses.Query.AdminWarehousesQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Warehouses.Queries.IGetWarehouseByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Warehouses.Query.AdminWarehousesQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Admin.Warehouses.Queries.IGetWarehousesQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Admin.Warehouses.Query.AdminWarehousesQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Authentication.Command.AuthenticationCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Authentication.Command.AuthenticationCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Authentication.Commands.IChangePasswordCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Authentication.Command.AuthenticationCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Authentication.Commands.ILoginCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Authentication.Command.AuthenticationCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Authentication.Commands.IRefreshTokenCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Authentication.Command.AuthenticationCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Authentication.Commands.IRegisterCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Authentication.Command.AuthenticationCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Authentication.Commands.IRevokeRefreshTokenCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Authentication.Command.AuthenticationCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Authentication.Commands.ISignOutCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Authentication.Command.AuthenticationCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Analytics.Query.CarrierAnalyticsQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Analytics.Query.CarrierAnalyticsQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Analytics.Queries.IGetCarrierRatingQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Analytics.Query.CarrierAnalyticsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Analytics.Queries.IGetCarrierRevenueQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Analytics.Query.CarrierAnalyticsQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Dashboard.Query.CarrierDashboardQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Dashboard.Query.CarrierDashboardQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Dashboard.Queries.IGetCarrierDashboardQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Dashboard.Query.CarrierDashboardQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Profile.Command.CarrierProfileCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Profile.Command.CarrierProfileCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Profile.Commands.IAddCarrierAdditionalInfoCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Profile.Command.CarrierProfileCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Profile.Commands.IUpdateCarrierProfileCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Profile.Command.CarrierProfileCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Profile.Query.CarrierProfileQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Profile.Query.CarrierProfileQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Profile.Queries.IGetCarrierProfileQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Profile.Query.CarrierProfileQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Shipments.Command.CarrierShipmentsCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Shipments.Command.CarrierShipmentsCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Shipments.Commands.ICompleteDeliveryCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Shipments.Command.CarrierShipmentsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Shipments.Commands.ICompletePickupCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Shipments.Command.CarrierShipmentsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Shipments.Commands.IUpdateCarrierStatusCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Shipments.Command.CarrierShipmentsCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Shipments.Query.CarrierShipmentsQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Shipments.Query.CarrierShipmentsQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Shipments.Queries.IGetCarrierShipmentByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Shipments.Query.CarrierShipmentsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Shipments.Queries.IGetCarrierShipmentsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Shipments.Query.CarrierShipmentsQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Trips.Query.CarrierTripsQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Trips.Query.CarrierTripsQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Trips.Queries.IGetCarrierTripByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Trips.Query.CarrierTripsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Carrier.Trips.Queries.IGetCarrierTripsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Carrier.Trips.Query.CarrierTripsQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Command.OperationManagerCarriersCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Command.OperationManagerCarriersCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Carriers.Commands.IAssignDeliveryCarrierCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Command.OperationManagerCarriersCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Carriers.Commands.IAssignPickupCarrierCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Command.OperationManagerCarriersCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Query.OperationManagerCarriersQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Query.OperationManagerCarriersQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Carriers.Queries.IFilterCarriersQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Query.OperationManagerCarriersQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Carriers.Queries.IGetCarrierByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Query.OperationManagerCarriersQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Carriers.Queries.IGetCarrierShipmentByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Query.OperationManagerCarriersQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Carriers.Queries.IGetCarrierShipmentsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Carriers.Query.OperationManagerCarriersQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Dashboard.Query.OperationManagerDashboardQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Dashboard.Query.OperationManagerDashboardQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Dashboard.Queries.IGetOperationManagerDashboardQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Dashboard.Query.OperationManagerDashboardQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Profile.Query.OperationManagerProfileQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Profile.Query.OperationManagerProfileQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Profile.Queries.IGetHandledCarriersQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Profile.Query.OperationManagerProfileQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Profile.Queries.IGetHandledShipmentsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Profile.Query.OperationManagerProfileQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Profile.Queries.IGetOperationManagerByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Profile.Query.OperationManagerProfileQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Command.OperationManagerShipmentsCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Command.OperationManagerShipmentsCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Shipments.Commands.IApproveShipmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Command.OperationManagerShipmentsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Shipments.Commands.IRejectShipmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Command.OperationManagerShipmentsCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Query.OperationManagerShipmentsQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Query.OperationManagerShipmentsQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Shipments.Queries.IFilterShipmentsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Query.OperationManagerShipmentsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Shipments.Queries.IGetAssignedShipmentsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Query.OperationManagerShipmentsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Shipments.Queries.IGetShipmentByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Query.OperationManagerShipmentsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Shipments.Queries.IGetShipmentHistoriesQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Query.OperationManagerShipmentsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Shipments.Queries.IGetShipmentReviewQueueQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Query.OperationManagerShipmentsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Shipments.Queries.IReviewShipmentQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Shipments.Query.OperationManagerShipmentsQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Trips.Command.OperationManagerTripsCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Trips.Command.OperationManagerTripsCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Trips.Commands.IStartDeliveryTripCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Trips.Command.OperationManagerTripsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Trips.Commands.IStartPickupTripCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Trips.Command.OperationManagerTripsCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Trips.Query.OperationManagerTripsQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Trips.Query.OperationManagerTripsQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Trips.Queries.IGetCarrierTripByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Trips.Query.OperationManagerTripsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.OperationManager.Trips.Queries.IGetCarrierTripsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.OperationManager.Trips.Query.OperationManagerTripsQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.Shared.Locations.Query.SharedLocationsQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.Shared.Locations.Query.SharedLocationsQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Shared.Locations.Queries.IGetCitiesByGovernmentQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Shared.Locations.Query.SharedLocationsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Shared.Locations.Queries.IGetCountriesQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Shared.Locations.Query.SharedLocationsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.Shared.Locations.Queries.IGetCountryGovernmentsQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.Shared.Locations.Query.SharedLocationsQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.CarrierRatings.Command.UserCarrierRatingsCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.User.CarrierRatings.Command.UserCarrierRatingsCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.CarrierRatings.Commands.IRateDeliveryCarrierCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.CarrierRatings.Command.UserCarrierRatingsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.CarrierRatings.Commands.IRatePickupCarrierCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.CarrierRatings.Command.UserCarrierRatingsCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Profile.Query.UserProfileQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Profile.Query.UserProfileQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Profile.Queries.IGetUserDashboardQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Profile.Query.UserProfileQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Profile.Queries.IGetUserProfileQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Profile.Query.UserProfileQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Command.UserShipmentsCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Command.UserShipmentsCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Shipments.Commands.ICancelShipmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Command.UserShipmentsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Shipments.Commands.ICreateShipmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Command.UserShipmentsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Shipments.Commands.IDeleteShipmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Command.UserShipmentsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Shipments.Commands.IIssueShipmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Command.UserShipmentsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Shipments.Commands.IUpdateShipmentCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Command.UserShipmentsCommand>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Query.UserShipmentsQuery>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Query.UserShipmentsQuery(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Shipments.Queries.IGetUserShipmentByIdQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Query.UserShipmentsQuery>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Shipments.Queries.ITrackShipmentQueryService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Shipments.Query.UserShipmentsQuery>());

        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Subscriptions.Command.UserSubscriptionsCommand>(serviceProvider => new global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Subscriptions.Command.UserSubscriptionsCommand(serviceProvider.GetRequiredService<IHttpHandler>(), serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient()));
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Subscriptions.Commands.ISubscribeToBundleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Subscriptions.Command.UserSubscriptionsCommand>());
        services.TryAddScoped<global::TransitNovaUI.BusinessLayer.ApiInterfaceServices.User.Subscriptions.Commands.IUnsubscribeFromBundleCommandService>(serviceProvider => serviceProvider.GetRequiredService<global::TransitNovaUI.BusinessLayer.ApiImplementation.User.Subscriptions.Command.UserSubscriptionsCommand>());

        return services;
    }
}
