using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace TransitNova.InfraStructure.Common.PdfGenerator.Helpers
{
    internal static class PdfPalette
    {
        public const string Navy = "#0F172A";
        public const string Blue = "#1D4ED8";
        public const string Slate = "#334155";
        public const string Muted = "#64748B";
        public const string Border = "#E2E8F0";
        public const string Surface = "#F8FAFC";
        public const string SoftBlue = "#EFF6FF";
        public const string SoftGreen = "#ECFDF5";
        public const string SoftRed = "#FEF2F2";
        public const string Green = "#047857";
        public const string Red = "#B91C1C";
    }

    internal static class PdfDocumentDesign
    {
        public const string CompanyName = "TransitNova";
        public const string Website = "www.transitnova.com";
        public const string Email = "finance@transitnova.com";
        public const string Phone = "+20 100 000 0000";
        public const string TaxNumber = "TN-EG-204-884-992";
        public const string Version = "1.0";

        public static TextStyle BaseTextStyle(TextStyle textStyle)
            => textStyle.FontSize(9).FontColor(PdfPalette.Slate);

        public static IContainer Card(IContainer container)
            => container.Border(1).BorderColor(PdfPalette.Border).Background(Colors.White).Padding(14);

        public static IContainer Section(IContainer container)
            => container.PaddingTop(12);

        public static IContainer TableHeader(IContainer container)
            => container.Background(PdfPalette.Navy).PaddingVertical(7).PaddingHorizontal(6)
                .DefaultTextStyle(style => style.FontColor(Colors.White).FontSize(8).Bold());

        public static IContainer TableCell(IContainer container, int index)
        {
            var background = index % 2 == 0 ? "#FFFFFF" : PdfPalette.Surface;
            return container.Background(background).BorderBottom(0.5f).BorderColor(PdfPalette.Border)
                .PaddingVertical(7).PaddingHorizontal(6);
        }

        public static void ComposeCompanyHeader(this IContainer container, string title, string subtitle, string generatedBy, string reportId)
        {
            container.Column(column =>
            {
                column.Item().Row(row =>
                {
                    row.ConstantItem(58).Height(58).Background(PdfPalette.Navy).AlignCenter().AlignMiddle()
                        .Text("TN").FontColor(Colors.White).FontSize(20).Bold();

                    row.RelativeItem().PaddingLeft(14).Column(identity =>
                    {
                        identity.Item().Text(CompanyName).FontSize(15).Bold().FontColor(PdfPalette.Navy);
                        identity.Item().Text(Website).FontSize(8).FontColor(PdfPalette.Muted);
                        identity.Item().Text($"{Email} | {Phone}").FontSize(8).FontColor(PdfPalette.Muted);
                        identity.Item().Text($"VAT / Tax Number: {TaxNumber}").FontSize(8).FontColor(PdfPalette.Muted);
                    });

                    row.RelativeItem().AlignRight().Column(meta =>
                    {
                        meta.Item().Text(title).FontSize(18).Bold().FontColor(PdfPalette.Navy);
                        meta.Item().Text(subtitle).FontSize(9).FontColor(PdfPalette.Muted);
                        meta.Item().PaddingTop(5).Text($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC").FontSize(8).FontColor(PdfPalette.Muted);
                        meta.Item().Text($"Generated by: {ValueOrDash(generatedBy)}").FontSize(8).FontColor(PdfPalette.Muted);
                        meta.Item().Text($"Report ID: {ValueOrDash(reportId)}").FontSize(8).FontColor(PdfPalette.Muted);
                        meta.Item().Text($"Version: {Version}").FontSize(8).FontColor(PdfPalette.Muted);
                    });
                });

                column.Item().PaddingTop(14).BorderBottom(1).BorderColor(PdfPalette.Border);
            });
        }

        public static void ComposeFooter(this IContainer container)
        {
            container.BorderTop(1).BorderColor(PdfPalette.Border).PaddingTop(8).Row(row =>
            {
                row.RelativeItem().Text($"{CompanyName} | Confidential business document")
                    .FontSize(8).FontColor(PdfPalette.Muted);

                row.RelativeItem().AlignCenter().Text($"Generated {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC")
                    .FontSize(8).FontColor(PdfPalette.Muted);

                row.RelativeItem().AlignRight().Text(text =>
                {
                    text.DefaultTextStyle(style => style.FontSize(8).FontColor(PdfPalette.Muted));
                    text.Span("Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                });
            });
        }

        public static void ComposeSummaryCard(this IContainer container, string label, string value, string hint, string accentColor = PdfPalette.Blue)
        {
            container.Border(1).BorderColor(PdfPalette.Border).Background(Colors.White).Padding(12).Column(column =>
            {
                column.Item().Text(label.ToUpperInvariant()).FontSize(7).SemiBold().FontColor(PdfPalette.Muted);
                column.Item().PaddingTop(4).Text(value).FontSize(16).Bold().FontColor(PdfPalette.Navy);
                column.Item().PaddingTop(4).Row(row =>
                {
                    row.ConstantItem(22).Height(3).Background(accentColor);
                    row.RelativeItem().PaddingLeft(7).Text(hint).FontSize(7).FontColor(PdfPalette.Muted);
                });
            });
        }

        public static void ComposeInfoLine(this IContainer container, string label, string value)
        {
            container.Row(row =>
            {
                row.ConstantItem(116).Text(label).FontSize(8).SemiBold().FontColor(PdfPalette.Muted);
                row.RelativeItem().Text(ValueOrDash(value)).FontSize(9).FontColor(PdfPalette.Navy);
            });
        }

        public static void ComposePlaceholder(this IContainer container, string title, string description)
        {
            container.Border(1).BorderColor(PdfPalette.Border).Background(PdfPalette.Surface).Padding(18)
                .AlignCenter().AlignMiddle().Column(column =>
                {
                    column.Item().AlignCenter().Text(title).FontSize(12).Bold().FontColor(PdfPalette.Navy);
                    column.Item().PaddingTop(5).AlignCenter().Text(description).FontSize(8).FontColor(PdfPalette.Muted);
                });
        }

        public static string ValueOrDash(string? value)
            => string.IsNullOrWhiteSpace(value) ? "-" : value;

        public static string Money(decimal value, object currency)
            => $"{value:N2} {currency}";

        public static string Date(DateTime? value)
            => value.HasValue ? value.Value.ToString("yyyy-MM-dd HH:mm") : "Pending";

        public static string ShortId(Guid value)
            => value == Guid.Empty ? "-" : value.ToString("N")[..8].ToUpperInvariant();
    }
}

